//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/GameOfLifeControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GameOfLife.Input
{
    public partial class @GameOfLifeControls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameOfLifeControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameOfLifeControls"",
    ""maps"": [
        {
            ""name"": ""GameOfLifeGame"",
            ""id"": ""897bce75-4fe5-48d8-a7ae-e449f9577425"",
            ""actions"": [
                {
                    ""name"": ""HoldPointer"",
                    ""type"": ""Button"",
                    ""id"": ""599608e8-760e-45e2-a9f1-1de98ce9db53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(pressPoint=0.5)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""eb0105bb-6e50-4bfc-aaa2-66d1e75a5a3f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""01137a14-ac3b-48b4-be7e-77b1e8ad05d0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldPointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1091f3bb-bece-4413-9a03-f868b481ce95"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // GameOfLifeGame
            m_GameOfLifeGame = asset.FindActionMap("GameOfLifeGame", throwIfNotFound: true);
            m_GameOfLifeGame_HoldPointer = m_GameOfLifeGame.FindAction("HoldPointer", throwIfNotFound: true);
            m_GameOfLifeGame_PointerPosition = m_GameOfLifeGame.FindAction("PointerPosition", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GameOfLifeGame
        private readonly InputActionMap m_GameOfLifeGame;
        private IGameOfLifeGameActions m_GameOfLifeGameActionsCallbackInterface;
        private readonly InputAction m_GameOfLifeGame_HoldPointer;
        private readonly InputAction m_GameOfLifeGame_PointerPosition;
        public struct GameOfLifeGameActions
        {
            private @GameOfLifeControls m_Wrapper;
            public GameOfLifeGameActions(@GameOfLifeControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @HoldPointer => m_Wrapper.m_GameOfLifeGame_HoldPointer;
            public InputAction @PointerPosition => m_Wrapper.m_GameOfLifeGame_PointerPosition;
            public InputActionMap Get() { return m_Wrapper.m_GameOfLifeGame; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameOfLifeGameActions set) { return set.Get(); }
            public void SetCallbacks(IGameOfLifeGameActions instance)
            {
                if (m_Wrapper.m_GameOfLifeGameActionsCallbackInterface != null)
                {
                    @HoldPointer.started -= m_Wrapper.m_GameOfLifeGameActionsCallbackInterface.OnHoldPointer;
                    @HoldPointer.performed -= m_Wrapper.m_GameOfLifeGameActionsCallbackInterface.OnHoldPointer;
                    @HoldPointer.canceled -= m_Wrapper.m_GameOfLifeGameActionsCallbackInterface.OnHoldPointer;
                    @PointerPosition.started -= m_Wrapper.m_GameOfLifeGameActionsCallbackInterface.OnPointerPosition;
                    @PointerPosition.performed -= m_Wrapper.m_GameOfLifeGameActionsCallbackInterface.OnPointerPosition;
                    @PointerPosition.canceled -= m_Wrapper.m_GameOfLifeGameActionsCallbackInterface.OnPointerPosition;
                }
                m_Wrapper.m_GameOfLifeGameActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @HoldPointer.started += instance.OnHoldPointer;
                    @HoldPointer.performed += instance.OnHoldPointer;
                    @HoldPointer.canceled += instance.OnHoldPointer;
                    @PointerPosition.started += instance.OnPointerPosition;
                    @PointerPosition.performed += instance.OnPointerPosition;
                    @PointerPosition.canceled += instance.OnPointerPosition;
                }
            }
        }
        public GameOfLifeGameActions @GameOfLifeGame => new GameOfLifeGameActions(this);
        public interface IGameOfLifeGameActions
        {
            void OnHoldPointer(InputAction.CallbackContext context);
            void OnPointerPosition(InputAction.CallbackContext context);
        }
    }
}
